spring:
  application:
    name: estate-empire-initiative
  datasource:
#    password: postgres
    url: jdbc:postgresql://localhost:5432/estate-empire-initiative
#    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  servlet:
    context-path: /api/v1
  port: 9990
