spring:
  application:
    name: estate-empire-initiative
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/estate-empire-initiative
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: estateempireinitiative@gmail.com
    password: estate@123
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
server:
  servlet:
    context-path: /api/v1
  port: 9990

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: 'true'
    beans:
      enabled: 'true'
    health:
      show-details: always
    metrics:
      enabled: 'true'
  prometheus:
    metrics:
      export:
        enabled: 'true'

